model:
  add_asker_id: true
  hidden_dim: 64
  n_heads: 4
  num_layers: 2
  dropout: 0.0

training:
  batchsize: 64
  epochs: 70
  learning_rate: 0.005
  weight_decay: 1e-5

data:
  root: "/mnt/lourens/data/agentsearch/data"
  percentage_lying: 0
  split_by: "question"  # options: "agent", "question"
  train_ratio: 0.6
  val_ratio: 0.2
  test_ratio: 0.2
  
experiment:
  seed: 42
  device: "cuda"
  use_wandb: false
  project_name: "agentsearch"
  experiment_name: "transformer"
  save_model: true
  model_save_path: "models/"

logging:
  log_level: "INFO"
  log_every: 10
