model:
  hidden_dim: 64
  num_layers: 3
  dropout: 0.0

training:
  batchsize: 2048
  epochs: 70
  learning_rate: 0.005
  weight_decay: 1e-5

data:
  root: "/mnt/lourens/data/agentsearch/data"
  percentage_lying: 0
  train_ratio: 0.6
  val_ratio: 0.2
  test_ratio: 0.2
  
experiment:
  seed: 42
  device: "cuda"
  use_wandb: true
  project_name: "agentsearch"
  experiment_name: "mlp"
  save_model: true
  model_save_path: "models/"

logging:
  log_level: "INFO"
  log_every: 10
