version: 2
updates:
# - package-ecosystem: docker
#   directory: "/"
#   schedule:
#     interval: daily
# - package-ecosystem: npm
#   directory: "/"
#   schedule:
#     interval: daily
#   ignore:
#   - dependency-name: aws-sdk
#     versions:
#     - "< 2.303"
#     - ">= 2.302.a"
#   - dependency-name: aws-sdk
#     versions:
#     - "> 2.482.0"
#     - "< 3"
#   - dependency-name: jsdom
#     versions:
#     - "> 11.12.0"
